query Authorization {
  authorization {
    scopes
  }
}

query FundingWallets {
  me {
    defaultAccount {
      defaultWallet {
        id
      }
      wallets {
        id
        walletCurrency
      }
    }
  }
}

query BlinkContacts {
  me {
    contacts {
      alias
      handle
      transactionsCount
    }
  }
}

fragment BlinkTransactionPaymentResult on Transaction {
  status
  direction
  settlementFee
  settlementCurrency
  settlementVia {
    ... on SettlementViaIntraLedger {
      preImage
    }
    ... on SettlementViaLn {
      preImage
    }
  }
}

mutation LnInvoicePaymentSend($input: LnInvoicePaymentInput!) {
  lnInvoicePaymentSend(input: $input) {
    status
    errors {
      message
      code
    }
    transaction {
      ...BlinkTransactionPaymentResult
    }
  }
}

mutation LnNoAmountInvoicePaymentSend($input: LnNoAmountInvoicePaymentInput!) {
  lnNoAmountInvoicePaymentSend(input: $input) {
    status
    errors {
      message
      code
    }
    transaction {
      ...BlinkTransactionPaymentResult
    }
  }
}

mutation LnNoAmountUsdInvoicePaymentSend($input: LnNoAmountUsdInvoicePaymentInput!) {
  lnNoAmountUsdInvoicePaymentSend(input: $input) {
    status
    errors {
      message
      code
    }
    transaction {
      ...BlinkTransactionPaymentResult
    }
  }
}
