#!/usr/bin/env python3
"""Export Rayl's RAILS artwork; requires CairoSVG, Pillow, and native Cairo."""

from copy import deepcopy
from io import BytesIO
from pathlib import Path
import re
import xml.etree.ElementTree as ET

import cairosvg
from PIL import Image, ImageDraw


BRANDING = Path(__file__).resolve().parent
APP = BRANDING.parent
RES = APP / "androidApp/src/main/res"
SVG = "{http://www.w3.org/2000/svg}"
SOURCE = ET.parse(BRANDING / "rails.svg").getroot()


def render(svg, size):
    data = cairosvg.svg2png(
        bytestring=ET.tostring(svg), output_width=size, output_height=size
    )
    return Image.open(BytesIO(data)).convert("RGBA")


def artwork(svg):
    return svg.find(f"{SVG}g[@id='artwork']")


def extend_rail(path):
    # Continue the decorative rays beyond the Android mask for launcher motion.
    # Keep the convergence point and gradient coordinates exactly as designed.
    points = re.fullmatch(
        r"M ([-\d.]+) ([-\d.]+) L ([-\d.]+) ([-\d.]+) L ([-\d.]+) ([-\d.]+) Z",
        path,
    )
    if points is None:
        raise ValueError(f"Expected a triangular rail, received: {path}")
    x, y, x1, y1, x2, y2 = map(float, points.groups())
    return (
        f"M {x:g} {y:g} L {2*x1-x:g} {2*y1-y:g} "
        f"L {2*x2-x:g} {2*y2-y:g} Z"
    )


def adaptive_layers():
    background = deepcopy(SOURCE)
    for group in list(artwork(background)):
        if group.get("id") != "background":
            artwork(background).remove(group)

    foreground = deepcopy(SOURCE)
    # 1024 artwork units occupy the central 72dp of Android's 108dp canvas.
    # The convergence point remains inside the central 66dp safe circle.
    foreground.set("viewBox", "-256 -256 1536 1536")
    art = artwork(foreground)
    art.attrib.pop("clip-path")
    art.remove(art.find(f"{SVG}g[@id='background']"))
    for rect in art.iter(f"{SVG}rect"):
        rect.attrib.update(x="-256", y="-256", width="1536", height="1536")
    for path in art.iter(f"{SVG}path"):
        path.set("d", extend_rail(path.get("d")))
    return background, foreground


def main():
    icon = render(SOURCE, 1024)
    if icon.getchannel("A").getextrema() != (255, 255):
        raise ValueError("The iOS and Play icon must be completely opaque")
    icon = icon.convert("RGB")
    icon.save(APP / "iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon.png")
    icon.resize((512, 512), Image.Resampling.LANCZOS).save(
        APP / "androidApp/src/main/ic_launcher-playstore.png"
    )

    background, foreground = adaptive_layers()
    for density, scale in [("mdpi", 1), ("hdpi", 1.5), ("xhdpi", 2),
                           ("xxhdpi", 3), ("xxxhdpi", 4)]:
        target = RES / f"mipmap-{density}"
        target.mkdir(parents=True, exist_ok=True)
        for name, layer in [("background", background), ("foreground", foreground)]:
            render(layer, int(108 * scale)).save(
                target / f"ic_launcher_{name}.webp", lossless=True, exact=True
            )

        # Legacy launchers (API 24–25) do not apply adaptive masks.
        for name, rounded in [("ic_launcher", False), ("ic_launcher_round", True)]:
            mask = Image.new("L", (1024, 1024))
            draw = ImageDraw.Draw(mask)
            if rounded:
                draw.ellipse((0, 0, 1023, 1023), fill=255)
            else:
                draw.rounded_rectangle((0, 0, 1023, 1023), radius=224, fill=255)
            legacy = icon.convert("RGBA")
            legacy.putalpha(mask)
            size = int(48 * scale)
            legacy.resize((size, size), Image.Resampling.LANCZOS).save(
                target / f"{name}.webp", lossless=True, exact=True
            )

    # Themed launcher icons use just the four solid planes, without glow.
    planes = [path.get("d") for path in artwork(foreground).iter(f"{SVG}path")
              if path.get("id", "").endswith("-plane")]
    paths = "\n".join(
        f'        <path android:fillColor="#FFFFFFFF" android:pathData="{p}" />'
        for p in planes
    )
    (RES / "drawable/ic_launcher_monochrome.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by apps/rayl/branding/export-icons.py. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="1536" android:viewportHeight="1536">\n'
        '    <group android:translateX="256" android:translateY="256">\n'
        f'{paths}\n    </group>\n</vector>\n'
    )


if __name__ == "__main__":
    main()
